name: Auto Request Review
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]
    branches: [master]

permissions:
  contents: read

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ruby/ruby' && github.base_ref == 'master' }}
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: necojackarc/auto-request-review@d340873f18ca7a85131f66b038a4ac1ebf9a3896 # master
        with:
          # scope: public_repo
          token: ${{ secrets.MATZBOT_AUTO_REQUEST_REVIEW_TOKEN }}
