name: Auto Request Review
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]
    branches: [master]

permissions:
  contents: read

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ruby/ruby' && github.base_ref == 'master' }}
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        # Using a fork until https://github.com/necojackarc/auto-request-review/pull/135 is merged
        uses: k0kubun/auto-request-review@0df295a0ff5c5d302770f589497280132131c63d # master
        with:
          # scope: public_repo
          token: ${{ secrets.MATZBOT_AUTO_REQUEST_REVIEW_TOKEN }}
